# Generated by Django 3.0.14 on 2025-06-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
        ('blog', '0004_enable_pg_trgm'),
    ]

    operations = [
    ]
